name: Docker Push Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Ver código en el mismo repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir las imágenes con el tag 
        run: |
          docker build -t luisardiles/videos-service:latest .
          docker tag luisardiles/videos-service:latest luisardiles/videos-service:${{ github.sha }}

      # 5. videos-service Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push luisardiles/videos-service:latest
          docker push luisardiles/videos-service:${{ github.sha }}